In [1]:
import math 

In [2]:
# ----------
# 
# In this exercise, you will put the finishing touches on a perceptron class.
#
# Finish writing the activate() method by using np.dot to compute signal
# strength and then add in a threshold for perceptron activation.
#
# ----------


import numpy as np


class Perceptron:
    """
    This class models an artificial neuron with step activation function.
    """

    def __init__(self, weights = np.array([1]), threshold = 0):
        """
        Initialize weights and threshold based on input arguments. Note that no
        type-checking is being performed here for simplicity.
        """
        self.weights = weights
        self.threshold = threshold
        print ("weight", weights)
        print ("threshold", threshold)
        
    def activate(self,inputs):
        """
        Takes in @param inputs, a list of numbers equal to length of weights.
        @return the output of a threshold perceptron with given inputs based on
        perceptron weights and threshold.
        """ 

        # INSERT YOUR CODE HERE

        # TODO: calculate the strength with which the perceptron fires
        print ("inputs", inputs)
        strength = np.dot(inputs, self.weights)
        print ("strength", strength)
        result = strength > self.threshold
        print ("result", result)
        # TODO: return 0 or 1 based on the threshold
            
        return result

def test():
    """
    A few tests to make sure that the perceptron class performs as expected.
    Nothing should show up in the output if all the assertions pass.
    """
    p1 = Perceptron(np.array([1, 2]), 0.)
    assert p1.activate(np.array([ 1,-1])) == 0 # < threshold --> 0
    assert p1.activate(np.array([-1, 1])) == 1 # > threshold --> 1
    assert p1.activate(np.array([ 2,-1])) == 0 # on threshold --> 0

if __name__ == "__main__":
    test()

('weight', array([1, 2]))
('threshold', 0.0)
('inputs', array([ 1, -1]))
('strength', -1)
('result', False)
('inputs', array([-1,  1]))
('strength', 1)
('result', True)
('inputs', array([ 2, -1]))
('strength', 0)
('result', False)


In [5]:
np.array([[2,0,-3]])

array([[ 2,  0, -3]])

In [4]:
np.array([1])

array([1])

In [27]:
class Perceptron:
    """
    This class models an artificial neuron with step activation function.
    """

    def __init__(self, weights = np.array([1]), threshold = 0):
        """
        Initialize weights and threshold based on input arguments. Note that no
        type-checking is being performed here for simplicity.
        """
        self.weights = weights
        self.threshold = threshold
        print weights
        print threshold
        
    def update(self, values, train, eta=.1):
        print values
        print train
        print eta
               

In [28]:
p1 = Perceptron(np.array([1,1,1]),0)
p1.update(np.array([[2,0,-3]]), np.array([1]))


[1 1 1]
0
[[ 2  0 -3]]
[1]
0.1


In [22]:
p2 = Perceptron(np.array([1,2,3]),0)
p2.update(np.array([[3,2,1],[4,0,-1]]),np.array([0,0]))

[1 2 3]
0
[[ 3  2  1]
 [ 4  0 -1]]
[0 0]
0.1


In [21]:
p3 = Perceptron(np.array([3,0,2]),0)
p3.update(np.array([[2,-2,4],[-1,-3,2],[0,2,1]]),np.array([0,1,0]))

[3 0 2]
0
[[ 2 -2  4]
 [-1 -3  2]
 [ 0  2  1]]
[0 1 0]
0.1


In [34]:
# ----------
#
# In this exercise, you will update the perceptron class so that it can update
# its weights.
#
# Finish writing the update() method so that it updates the weights according
# to the perceptron update rule.
# 
# ----------

import numpy as np


class Perceptron:
    """
    This class models an artificial neuron with step activation function.
    """

    def __init__(self, weights = np.array([1]), threshold = 0):
        """
        Initialize weights and threshold based on input arguments. Note that no
        type-checking is being performed here for simplicity.
        """
        self.weights = weights.astype(float)
        self.threshold = threshold


    def activate(self, values):
        """
        Takes in @param values, a list of numbers equal to length of weights.
        @return the output of a threshold perceptron with given inputs based on
        perceptron weights and threshold.
        """
               
        # First calculate the strength with which the perceptron fires
        strength = np.dot(values,self.weights)
        
        # Then return 0 or 1 depending on strength compared to threshold  
        return int(strength > self.threshold)


    def update(self, values, train, eta=.1):
        """
        Takes in a 2D array @param values consisting of a LIST of inputs and a
        1D array @param train, consisting of a corresponding list of expected
        outputs. Updates internal weights according to the perceptron training
        rule using these values and an optional learning rate, @param eta.
        """

        # YOUR CODE HERE

        # TODO: for each data point...
        
            # TODO: obtain the neuron's prediction for that point

            # TODO: update self.weights based on prediction accuracy, learning
            # rate and input value
            
        for (i,item) in enumerate(train):
            train_hat = self.activate(values[i])
            for (j, weight) in enumerate(self.weights):
               self.weights[j] = self.weights[j] + ( eta * (train[i] - train_hat) ) * values[i][j]



In [4]:
def test():
    """
    A few tests to make sure that the perceptron class performs as expected.
    Nothing should show up in the output if all the assertions pass.
    """
    def sum_almost_equal(array1, array2, tol = 1e-6):
        return sum(abs(array1 - array2)) < tol

    p1 = Perceptron(np.array([1,1,1]),0)
    p1.update(np.array([[2,0,-3]]), np.array([1]))
    assert sum_almost_equal(p1.weights, np.array([1.2, 1, 0.7]))
    
    p2 = Perceptron(np.array([1,2,3]),0)
    p2.update(np.array([[3,2,1],[4,0,-1]]),np.array([0,0]))
    assert sum_almost_equal(p2.weights, np.array([0.7, 1.8, 2.9]))

    p3 = Perceptron(np.array([3,0,2]),0)
    p3.update(np.array([[2,-2,4],[-1,-3,2],[0,2,1]]),np.array([0,1,0]))
    assert sum_almost_equal(p3.weights, np.array([2.7, -0.3, 1.7]))

NameError: name 'Perceptron' is not defined